export const REGDETAILPAGE: any[] = 
[{id:2,
  language:'English',
  regdetail_h1: 'details',
  regdetail_id: 'id',
  regdetail_description: 'description',
  regdetail_name: 'name',
  regdetail_createTime:'createTime',
  regdetail_regFind1: 'regFind',
  regdetail_regScope: 'regScope',
  regdetail_regFind: 'regFind',
  regdetail_regReplace: 'regReplace',
  regdetail_regScopeAttr: 'ScopeAttr',
  regdetail_regFindAttr: 'FindAttr',
  regdetail_back: 'Back',
  regdetail_save: 'Save'
},
{ id:1,
  language:'中文',
  regdetail_h1: '详细',
  regdetail_id: 'id',
  regdetail_description: '说明',
  regdetail_name: '标题',
  regdetail_createTime:'创建时间',
  regdetail_regFind1: '接单人',
  regdetail_regScope: '目标表达式',
  regdetail_regFind: '查找表达式',
  regdetail_regReplace: '替换为',
  regdetail_regScopeAttr: '目标属性',
  regdetail_regFindAttr: '查找属性',
  regdetail_back: '后退',
  regdetail_save: '保存'
}];