export const WORKSPACEPAGE: any[] = 
[{id: 2,
  language: 'English',
  workspace_h1: 'details',
  workspace_id: 'id',
  workspace_category: 'category',
  workspace_area: 'area',
  workspace_subarea: 'subarea',
  workspace_employee: 'employee',
  workspace_reglist: 'Rules',
  workspace_name: 'name',
  workspace_assigneeid: 'assigneeid',
  workspace_assignee: 'assignee',
  workspace_reply: 'reply',
  workspace_filelist: 'filelist',
  workspace_back: 'back',
  workspace_save: 'save'
},
{ id: 1,
  language: '中文',
  workspace_h1: '详细',
  workspace_id: 'id',
  workspace_category: '类别',
  workspace_area: '区域',
  workspace_subarea: '子区域',
  workspace_employee: '拥有者',
  workspace_reglist: '规则列表',
  workspace_name: '标题',
  workspace_assigneeid: '接单人id',
  workspace_assignee: '接单人',
  workspace_reply: '回复',
  workspace_filelist: '文件列表',
  workspace_back: '返回',
  workspace_save: '保存'
}]